steps:
  # Step 1: SSH into the remote VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'new-instance'  # Replace with your VM instance name
      - '--zone'
      - 'asia-south1-a'  # Replace with your VM's zone
      - '--project'
      - 'jmc-devsecops'  # Replace with your GCP project ID
      - '--command'
      - 'hostname'
 

  - name: 'gcr.io/cloud-builders/helm:latest'
    args: ['repo', 'add', 'prometheus-community', 'https://prometheus-community.github.io/helm-charts']
  # - name: 'gcr.io/cloud-builders/helm'
  #   args: ['repo', 'update']
  # - name: 'gcr.io/cloud-builders/helm'
  #   args: ['install', 'prometheus', '--namespace', 'monitoring', '--wait', 'prometheus-community/prometheus', # Optional: Add custom values with `--set` flag
  #          '--set', 'server.retention.days=30']
  # - name: 'gcr.io/jmc-devsecops/cloud-builders-helm'
  #   args:
  #     - 'helm' 
  #     - 'search'
  #     - 'hub'
  #     - 'prometheus'



